# Generated by Django 3.1.1 on 2020-12-07 22:41

from django.db import migrations
import django_resized.forms
import material.models
import material.storage


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, quality=85, size=(400, 400), storage=material.storage.OverwriteStorage(), upload_to=material.models.get_avatar_file_path),
        ),
    ]
