# Generated by Django 3.1.1 on 2020-12-25 21:47

from django.db import migrations, models
import material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='video_en',
            field=models.FileField(blank=True, upload_to=material.models.get_video_file_path),
        ),
        migrations.AddField(
            model_name='section',
            name='video_fi',
            field=models.FileField(blank=True, upload_to=material.models.get_video_file_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='material.Lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be able to log in. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether this user should have full read and write access to all data.', verbose_name='superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be able to manage data about their organization and its members.', verbose_name='Organization supervisor'),
        ),
    ]
