# Generated by Django 3.1.1 on 2021-02-14 22:35

from django.db import migrations, models
import django.db.models.deletion
import material.blocks
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtailvideos.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('description_en', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('description_fi', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('description_en', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('description_fi', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('body', wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('video', wagtailvideos.blocks.VideoChooserBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock()), ('quiz', material.blocks.QuizBlock()), ('open_question', wagtail.core.blocks.RichTextBlock())], blank=True)),
                ('body_en', wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('video', wagtailvideos.blocks.VideoChooserBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock()), ('quiz', material.blocks.QuizBlock()), ('open_question', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
                ('body_fi', wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('video', wagtailvideos.blocks.VideoChooserBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock()), ('quiz', material.blocks.QuizBlock()), ('open_question', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('body_en', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('body_fi', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='organization',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='material.Lesson'),
        ),
    ]
