# Generated by Django 3.1.1 on 2021-01-30 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import material.models
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    replaces = [('material', '0002_auto_20210130_1532'), ('material', '0003_auto_20210130_1709'), ('material', '0004_auto_20210130_1817'), ('material', '0005_auto_20210130_1836'), ('material', '0006_auto_20210130_1847'), ('material', '0007_remove_quiz_lesson')]

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True, max_length=250)),
                ('text_fi', models.CharField(blank=True, max_length=250)),
                ('correct', models.BooleanField(default=False)),
                ('explanation_en', models.CharField(blank=True, max_length=250)),
                ('explanation_fi', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True, max_length=250)),
                ('text_fi', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(blank=True)),
                ('text_fi', models.TextField(blank=True)),
                ('video_en', models.FileField(blank=True, upload_to=material.models.get_video_file_path)),
                ('video_fi', models.FileField(blank=True, upload_to=material.models.get_video_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.openquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='openquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='material.section'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.multiplechoiceanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True, max_length=250)),
                ('text_fi', models.CharField(blank=True, max_length=250)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='material.section')),
            ],
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='material.multiplechoicequestion'),
        ),
        migrations.CreateModel(
            name='LessonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('body', wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock())], blank=True)),
                ('sections', models.ManyToManyField(through='material.Content', to='material.Section')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.lessonpage'),
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.section'),
        ),
        migrations.AddField(
            model_name='organization',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='material.LessonPage'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_sections',
            field=models.ManyToManyField(blank=True, through='material.SectionCompletion', to='material.Section'),
        ),
        migrations.AddConstraint(
            model_name='sectioncompletion',
            constraint=models.UniqueConstraint(fields=('user', 'section'), name='unique_completion_for_user_and_section'),
        ),
        migrations.AddConstraint(
            model_name='openquestionresponse',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_response_for_user_and_question'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='openquestion',
            order_with_respect_to='section',
        ),
        migrations.AddConstraint(
            model_name='multiplechoiceresponse',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_response_for_user_and_answer'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='multiplechoicequestion',
            order_with_respect_to='section',
        ),
        migrations.AlterOrderWithRespectTo(
            name='multiplechoiceanswer',
            order_with_respect_to='question',
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('lesson', 'section'), name='no_duplicate_sections_per_lesson'),
        ),
        migrations.RemoveField(
            model_name='sectioncompletion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectioncompletion',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='multiplechoiceanswer',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='openquestion',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='lessonpage',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_sections',
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='lesson',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='material.lessonpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='lesson',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='material.lessonpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openquestion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='material.multiplechoicequestion'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='multiplechoiceanswer',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='multiplechoicequestion',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='openquestion',
            order_with_respect_to=None,
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='SectionCompletion',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock()), ('quiz', wagtail.snippets.blocks.SnippetChooserBlock('Quiz'))], blank=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='material.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock()), ('quiz', wagtail.snippets.blocks.SnippetChooserBlock('material.Quiz'))], blank=True),
        ),
    ]
