# Generated by Django 3.1.1 on 2021-01-30 15:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20210130_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncompletion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectioncompletion',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='multiplechoiceanswer',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='openquestion',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='lessonpage',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_sections',
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='lesson',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='material.lessonpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='lesson',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='material.lessonpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openquestion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='material.multiplechoicequestion'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='multiplechoiceanswer',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='multiplechoicequestion',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='openquestion',
            order_with_respect_to=None,
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='SectionCompletion',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
