# Generated by Django 3.1.8 on 2021-04-25 22:02

from django.db import migrations
import material.blocks
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('media', material.blocks.MediaChooserBlock()), ('quiz', material.blocks.QuizChooserBlock()), ('open_question', material.blocks.OpenQuestionChooserBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='body_en',
            field=wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('media', material.blocks.MediaChooserBlock()), ('quiz', material.blocks.QuizChooserBlock()), ('open_question', material.blocks.OpenQuestionChooserBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='body_fi',
            field=wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('media', material.blocks.MediaChooserBlock()), ('quiz', material.blocks.QuizChooserBlock()), ('open_question', material.blocks.OpenQuestionChooserBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock())], blank=True, null=True),
        ),
    ]
