# Generated by Django 3.1.1 on 2020-12-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20201225_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='password_reset_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
