# Generated by Django 3.1.1 on 2021-01-30 16:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20210130_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.core.fields.StreamField([('lesson_content', wagtail.core.blocks.RichTextBlock()), ('page_break', wagtail.core.blocks.static_block.StaticBlock()), ('quiz', wagtail.snippets.blocks.SnippetChooserBlock('Quiz'))], blank=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='material.lessonpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='material.quiz'),
            preserve_default=False,
        ),
    ]
