# Generated by Django 3.1.1 on 2020-11-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20201121_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='staticpage',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='staticpage',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='answer',
            name='text_fi',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_fi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_fi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='text_fi',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='section',
            name='text_fi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_fi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_fi',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
