# Generated by Django 3.1.1 on 2020-12-13 12:44

from django.db import migrations, models
import material.models
import material.storage


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20201210_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, storage=material.storage.OverwriteStorage(), upload_to=material.models.get_logo_file_path),
        ),
    ]
