# Generated by Django 3.1.1 on 2021-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_add_permissions_mixin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
