# Generated by Django 3.1.1 on 2021-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20210130_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='internal_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
