# Generated by Django 3.1.1 on 2020-12-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20201130_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='MultipleChoiceAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='MultipleChoiceQuestion',
        ),
        migrations.RenameModel(
            old_name='QuestionResponse',
            new_name='MultipleChoiceResponse',
        ),
    ]
