# Generated by Django 3.1.1 on 2020-12-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20201202_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='material.section'),
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True, max_length=250)),
                ('text_fi', models.CharField(blank=True, max_length=250)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='material.section')),
            ],
            options={
                'order_with_respect_to': 'section',
            },
        ),
    ]
