# Generated by Django 3.1.1 on 2020-12-02 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20201202_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.openquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='openquestionresponse',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_response_for_user_and_question'),
        ),
    ]
