# Generated by Django 3.1.1 on 2020-12-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_auto_20201203_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
